- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: Install useful packages
  apt:
    name:
      - sysstat
      - iotop
      - vim
    state: present
    force: yes
